### PR TITLE
Minor filesystem support expansion 

### PR DESCRIPTION
**Pull request by dalto8**
Expand the list of filesystems currently supported

### CODE REVIEW

**Review by killajoe — COMMENTED** [review]
we will produce a lot of traffic on the forum with this commit ;)

**Review by killajoe — CHANGES_REQUESTED** [review]
http://fsfs.sourceforge.net/
interesting one..

**Comment by dalto8** [comment]
> we will produce a lot of traffic on the forum with this commit ;)

Especially when people try to do an install on the `fat12` filesystem....

**Comment by dalto8** [comment]
Maybe this is more reasonable now?

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/EndeavourOS-calamares/blob/b34d1c0c091bf17d7fe92367c203132689822c56/calamares/modules/partition.conf#L42

**Pull request closed without merging**
